version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: "forecast_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forecast
      POSTGRES_PASSWORD: forecast
      POSTGRES_DB: forecast
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@default.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    container_name: "forecast_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  weather-web-service:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgres://forecast:forecast@forecast_postgres:5432/forecast?sslmode=disable"
      REDIS_URL: "redis://redis/"

volumes:
  postgres_data:
  redis_data: